services:
  Javawebcalculator:
    build:
      context: ./JavaWebCalculator
    image: JavaWebCalculator:latest    # ✅ Added image name
    ports:
      - "8080:8080"
    container_name: JavaWebCalculator

  vprofile:
    build:
      context: ./vprofile-project
    image: vprofile:latest             # ✅ Added image name
    ports:
      - "8081:8080"
    container_name: vprofile
