version: "3.8"

services:
  javawebcalculator:
    build:
      context: ./javawebcalculator
    image: javawebcalculator:latest    # ✅ Added image name
    ports:
      - "8080:8080"
    container_name: javawebcalculator

  vprofile:
    build:
      context: ./vprofile
    image: vprofile:latest             # ✅ Added image name
    ports:
      - "8081:8080"
    container_name: vprofile

    sample-java-project:
    build:
      context: ./sample-java-project
    image: sample-java-project:latest
    ports:
      - "8082:8080"
     container_name: sample-java-project
