version: "3.8"

services:
  javawebcalculator:
    build:
      context: ./javawebcalculator
    image: javawebcalculator:latest
    ports:
      - "8080:8080"
    container_name: javawebcalculator

  vprofile:
    build:
      context: ./vprofile
    image: vprofile:latest
    ports:
      - "8081:8080"
    container_name: vprofile

  sample-java-project:
    build:
      context: ./sample-java-project
    image: sample-java-project:latest
    ports:
      - "8082:8080"
    container_name: sample-java-project

  livejava-project:
    build:
      context: ./livejava-project
    image: livejava-project:latest
    ports:
      - "8083:8080"
    container_name: livejava-project
